sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y ttf-mscorefonts-installer dvipng texlive-full
script:
- make
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  file:
  - markless.pdf
  on:
    branch: master
    tags: true